const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const ANON_KEY=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY||'';
const H=k=>({apikey:k,Authorization:'Bearer '+k,'Content-Type':'application/json'});
async function user(t){const r=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:ANON_KEY,Authorization:'Bearer '+t}});const d=await r.json().catch(()=>null);if(!r.ok||!d?.id)throw Error('Session expired.');return d}
async function sb(p,o={}){const r=await fetch(SUPABASE_URL+p,{method:o.method||'GET',headers:{...H(SERVICE_KEY),...(o.headers||{})},body:o.body===undefined?undefined:JSON.stringify(o.body)});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.hint||d?.error||('Supabase '+r.status));return d}
async function audit(u,t,status,details={}){return sb('/rest/v1/ai_audit_log',{method:'POST',body:{user_id:u.id,role:'landlord',action:'care_task',action_type:t.task_type,status,target_type:t.target_type,target_id:t.target_id,details:{task_id:t.id,...details},requires_confirmation:true,confirmed_by:u.id,confirmed_at:new Date().toISOString()}})}
async function run(u,t){if(!['rent_reminder','maintenance_followup'].includes(t.task_type))throw Error('This task requires a dedicated confirmation flow.');
if(t.task_type==='rent_reminder'){const r=(await sb('/rest/v1/rent_records?select=id,tenant_id,amount_due,amount_paid&id=eq.'+encodeURIComponent(t.target_id)+'&limit=1'))[0];if(!r?.tenant_id)throw Error('Rent record or tenant not found.');const x=(await sb('/rest/v1/tenants?select=profile_id&id=eq.'+encodeURIComponent(r.tenant_id)+'&landlord_id=eq.'+encodeURIComponent(u.id)+'&limit=1'))[0];if(!x?.profile_id)throw Error('Tenant profile not found.');const b=Math.max(0,Number(r.amount_due||0)-Number(r.amount_paid||0));await sb('/rest/v1/notifications',{method:'POST',body:{user_id:x.profile_id,title:'MavRent rent reminder',message:'Your outstanding rent balance is '+b.toLocaleString()+' UGX. Please check MavRent for details.',type:'payment',related_id:r.id}});return 'In-app rent reminder delivered to tenant.'}
const m=(await sb('/rest/v1/maintenance_requests?select=id,title&id=eq.'+encodeURIComponent(t.target_id)+'&landlord_id=eq.'+encodeURIComponent(u.id)+'&limit=1'))[0];if(!m)throw Error('Maintenance request not found.');await sb('/rest/v1/notifications',{method:'POST',body:{user_id:u.id,title:'Maintenance follow-up',message:(m.title||'Open maintenance request')+' needs attention.',type:'maintenance',related_id:m.id}});return 'In-app maintenance follow-up delivered to landlord.'}
module.exports=async(req,res)=>{try{if(!SERVICE_KEY)return res.status(500).json({error:'SUPABASE_SERVICE_ROLE_KEY is not configured.'});const u=await user(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));const p=(await sb('/rest/v1/profiles?select=id,role&id=eq.'+encodeURIComponent(u.id))).find(x=>x.id===u.id);if(!p||p.role!=='landlord')return res.status(403).json({error:'Care Tasks are landlord-only.'});
if(req.method==='GET'){const tasks=await sb('/rest/v1/ai_care_tasks?select=*&landlord_id=eq.'+encodeURIComponent(u.id)+'&status=eq.prepared&order=priority.desc,created_at.desc&limit=100');return res.json({tasks:tasks||[]})}
if(req.method!=='POST')return res.status(405).json({error:'GET or POST required'});const id=req.body?.task_id,dec=req.body?.decision;
if(dec==='approve_all'){const ts=await sb('/rest/v1/ai_care_tasks?select=*&landlord_id=eq.'+encodeURIComponent(u.id)+'&status=eq.prepared&order=priority.desc,created_at.asc&limit=100');const z={approved:0,executed:0,failed:0,blocked:0,results:[]};for(const t of ts||[]){if(!['rent_reminder','maintenance_followup'].includes(t.task_type)){z.blocked++;z.results.push({id:t.id,status:'blocked'});continue}z.approved++;try{const msg=await run(u,t);await sb('/rest/v1/ai_care_tasks?id=eq.'+encodeURIComponent(t.id)+'&landlord_id=eq.'+encodeURIComponent(u.id),{method:'PATCH',body:{status:'executed',executed_at:new Date().toISOString()}});await audit(u,t,'executed',{bulk:true,execution:msg});z.executed++;z.results.push({id:t.id,status:'executed',message:msg})}catch(e){await sb('/rest/v1/ai_care_tasks?id=eq.'+encodeURIComponent(t.id)+'&landlord_id=eq.'+encodeURIComponent(u.id),{method:'PATCH',body:{status:'failed'}}).catch(()=>null);await audit(u,t,'failed',{bulk:true,error:e.message}).catch(()=>null);z.failed++;z.results.push({id:t.id,status:'failed',message:e.message})}}await sb('/rest/v1/ai_audit_log',{method:'POST',body:{user_id:u.id,role:'landlord',action:'care_tasks_bulk',action_type:'approve_all',status:'executed',details:z,requires_confirmation:true,confirmed_by:u.id,confirmed_at:new Date().toISOString()}});return res.json({ok:true,...z})}
if(!id||!['approve','skip'].includes(dec))return res.status(400).json({error:'task_id and approve/skip are required.'});const rows=await sb('/rest/v1/ai_care_tasks?select=*&id=eq.'+encodeURIComponent(id)+'&landlord_id=eq.'+encodeURIComponent(u.id)+'&status=eq.prepared&limit=1'),t=rows[0];if(!t)return res.status(404).json({error:'Prepared Care Task not found.'});
if(dec==='skip'){await sb('/rest/v1/ai_care_tasks?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:{status:'skipped'}});await audit(u,t,'skipped');return res.json({ok:true,message:'Task skipped.'})}
try{const msg=await run(u,t);await sb('/rest/v1/ai_care_tasks?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:{status:'executed',executed_at:new Date().toISOString()}});await audit(u,t,'executed',{execution:msg});return res.json({ok:true,message:msg})}catch(e){await sb('/rest/v1/ai_care_tasks?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:{status:'failed'}}).catch(()=>null);await audit(u,t,'failed',{error:e.message}).catch(()=>null);return res.status(500).json({error:e.message})}
}catch(e){return res.status(500).json({error:e.message||'Care Tasks failed.'})}};